#!/usr/bin/env python
import sys
import os
from subprocess import call

if (os.path.isfile("TAGS")):
    call(["rm","TAGS"])

iterdeps = iter(sys.argv)
next(iterdeps)
for dep in iterdeps:
    if (os.path.isfile(dep)):
        fd = open(dep,'r')
    else:
        sys.exit("Could not open %s"%(dep))
    line = fd.readline()
    while line:
        linelist = line.split(" ")
        for s in linelist:
            if (s.find(".cpp") != -1) or \
               (s.find(".c") != -1) or \
               (s.find(".h") != -1):
                srelative = s.replace('../','')
                if os.path.isfile(srelative):
                    call(["etags","--append",srelative])
        line = fd.readline()

   

